---
- name: Copy NVM Stuff
  win_copy:
    src: files/NVM_ServiceProfile.xml
    dest: 'C:\ProgramData\Cisco\Cisco AnyConnect Secure Mobility Client\NVM\NVM_ServiceProfile.xml'

- name: Copy AC Profile
  win_copy:
    src: files/acvpn.xml
    dest: 'C:\ProgramData\Cisco\Cisco AnyConnect Secure Mobility Client\Profile\acvpn.xml'

- name: Add APT32 Zone for chinabytes.info
  win_shell: 'Add-DnsServerPrimaryZone -Name "chinabytes.info" -ReplicationScope "Forest" -PassThru'
  ignore_errors: yes

- name: Powershell Add Record
  win_shell: Add-DnsServerResourceRecordA -Name "images" -ZoneName "chinabytes.info" -AllowUpdateAny -IPv4Address "198.18.133.60" -TimeToLive 01:00:00
  ignore_errors: yes

# Ansible 2.8 or greater :(
#- name: add apt32 domains
#  win_dns_record: 
#    name: "images"
#    type: "A"
#    value: "198.18.133.60"
#    zone: "chinabytes.info"


