---
- name: Copy NVM Stuff
  win_copy:
    src: files/NVM_ServiceProfile.xml
    dest: 'C:\ProgramData\Cisco\Cisco AnyConnect Secure Mobility Client\NVM\NVM_ServiceProfile.xml'

- name: Copy AC Profile
  win_copy:
    src: files/acvpn.xml
    dest: 'C:\ProgramData\Cisco\Cisco AnyConnect Secure Mobility Client\Profile\acvpn.xml'

- name: Add APT32 Zone for chinabytes.info
  win_shell: 'Add-DnsServerPrimaryZone -Name "chinabytes.info" -ReplicationScope "Forest" -PassThru'
  ignore_errors: yes

- name: Powershell Add Record for images.chinabytes.info
  win_shell: Add-DnsServerResourceRecordA -Name "images" -ZoneName "chinabytes.info" -AllowUpdateAny -IPv4Address "198.18.133.49" -TimeToLive 01:00:00
  ignore_errors: yes

- name: Add APT32 Zone for codehao.net
  win_shell: 'Add-DnsServerPrimaryZone -Name "codehao.net" -ReplicationScope "Forest" -PassThru'
  ignore_errors: yes

- name: Powershell Add Record for share.codehao.net
  win_shell: Add-DnsServerResourceRecordA -Name "share" -ZoneName "codehao.net" -AllowUpdateAny -IPv4Address "198.18.133.60" -TimeToLive 01:00:00
  ignore_errors: yes

- name: Add APT32 Zone for supperpow.com
  win_shell: 'Add-DnsServerPrimaryZone -Name "supperpow.com" -ReplicationScope "Forest" -PassThru'
  ignore_errors: yes

- name: Powershell Add Record for job.supperpow.com
  win_shell: Add-DnsServerResourceRecordA -Name "job" -ZoneName "supperpow.com" -AllowUpdateAny -IPv4Address "198.18.133.49" -TimeToLive 01:00:00
  ignore_errors: yes

- name: Add APT32 Zone for yiihao126.net
  win_shell: 'Add-DnsServerPrimaryZone -Name "yiihao126.net" -ReplicationScope "Forest" -PassThru'
  ignore_errors: yes

- name: Powershell Add Record for yii.yiihao126.net
  win_shell: Add-DnsServerResourceRecordA -Name "yii" -ZoneName "yiihao126.net" -AllowUpdateAny -IPv4Address "198.18.133.49" -TimeToLive 01:00:00
  ignore_errors: yes


# Ansible 2.8 or greater :(
#- name: add apt32 domains
#  win_dns_record: 
#    name: "images"
#    type: "A"
#    value: "198.18.133.49"
#    zone: "chinabytes.info"


