---
- hosts: oob
  connection: local
  become: yes
  become_user: root

  roles:
  - oob

- hosts: kali
  become: yes
  become_user: root

  roles:
  - kali

- hosts: windows

  roles:
  - windows

- hosts: asa
  vars:
    cli:
      # host: "{{ inventory_hostname }}"
      username: admin
      password: C1sco12345
      authorize: yes
      auth_pass: C1sco123453

  roles:
  - asa

