---
- hosts: oob
  connection: local
  become: yes
  become_user: root

  roles:
  - oob

- hosts: kali
  become: yes
  become_user: root

  roles:
  - kali

- hosts: windows

  roles:
  - windows

- hosts: attackerc2
  become: yes
  become_user: root

  roles:
  - attackerc2
